### ISSUE TITLE
A problem when execute the program

### ISSUE THREAD

**Issue by baojunshan** [phv2312/AA#1]
I just run `main.py`, and the terminal shows:
'''
Traceback (most recent call last):
  File "main.py", line 133, in <module>
    main()
  File "main.py", line 80, in main
    mesh = tri_mc.create(image, mask)
  File "/home/baojunshan/AA/lib/mc/mc.py", line 34, in create
    sampling_points = mc_utils.sampling_points(image, mask, interval=self.interval)
  File "/home/baojunshan/AA/lib/mc/mc_utils.py", line 17, in sampling_points
    boundary_points = boundary_contour[::int(interval), 0, :].astype(np.int)
IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed
'''

**Comment by baojunshan** [comment]
I get it!, This causes by the cv2 version, when use `cv2.findContours`. I fixed problem in the PR #2

**Comment by phv2312** [comment]
Thanks you for your contribution
